/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package roctpaperscissors

import enums.MOVES
import players.Player
import games.RockPaperScissors
import strategies.PlayStrategy
import strategies.RandomMoveStrategy
import strategies.ConstantMoveStrategy
import strategies.ScoreCalculationStrategy
import strategies.NormalCalculationStrategy
import scoreboards.Scoreboard
import strategies.NormalDisplayScoreStrategy

fun main() {
    val firstPlayer : Player = Player("playerA", RandomMoveStrategy())
    val secondPlayer : Player = Player("PlayerB", ConstantMoveStrategy(MOVES.ROCK))
    val game : RockPaperScissors = RockPaperScissors(NormalCalculationStrategy(), firstPlayer, secondPlayer)
    val rounds : Int = 100
    game.start(rounds)
    val scoreBoard : Scoreboard = Scoreboard(NormalDisplayScoreStrategy())
    scoreBoard.show(firstPlayer.getPlayerInfoCard(), secondPlayer.getPlayerInfoCard())
}
