/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package roctpaperscissors

import enumtests.MOVESTest
import enumtests.RESULTSTest
// import org.junit.jupiter.api.Assertions.assertEquals
// import org.junit.jupiter.api.Test
import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertEquals

class AppTest {
    val movesTest = MOVESTest()
    val resultsTest = RESULTSTest()
}
