/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package roctpaperscissors

import enumtests.MOVESTest
import enumtests.RESULTSTest
import strategiestests.RandMoveStrategyTest
import strategiestests.ConstMoveStrategyTest


class AppTest {
    val movesTest = MOVESTest()
    val resultsTest = RESULTSTest()
    val randMoveStrategyTest = RandMoveStrategyTest()
    val constMoveStrategyTest = ConstMoveStrategyTest()
}
